language: php
php:
  - 5.4
  - 5.5
  - 5.6
addons:
  code_climate:
    repo_token: 37497289099dc1e7d043ee5d3dc59a63c9c041e78b2c91f4394d0b1cb8e74ff7
before_script:
  - sed -i '/phpdocumentor/d' composer.json
  - composer install
script: phpunit --configuration tests/phpunit.xml tests
after_script:
  - vendor/bin/test-reporter